sprint5
Nchezhegova/market pull request #1
Opened 2024-02-27 07:49 UTC by Nchezhegova

2024-02-29 16:17 UTC, tmvrus requested changes
- своих тестов нет
- чужие тесты не проходят

2024-02-29 16:17 UTC, tmvrus commented on internal/http/handlers/balance.go
> +	}
- вот этот кусок повторяется несколько раз в разных хендлерах, это вполне тянет на middleware
- StatusBadRequest не самый лучший выбор, тут больше подойдет StatusUnauthorized (а задании есть соответствующее требование)

2024-02-29 16:17 UTC, tmvrus commented on internal/models/balance.go
> +//}
закоментированный код - это признак небрежного отношения к рабте

2024-02-29 16:17 UTC, tmvrus commented on internal/models/order.go
> +//}
такое обычно делают в методе String() string у типа
https://go.dev/tour/methods/17

2024-02-29 16:17 UTC, tmvrus commented on internal/http/handlers/balance.go
> +	c.Data(http.StatusOK, "application/json", balanceByte)
если я ничего не путаю, то gin умеет сам отправить json
```
c.JSON(status, any)
```

2024-02-29 16:17 UTC, tmvrus commented on internal/http/handlers/balance.go
> +	}
io.ReadAll(c.Request.Body) и промежуточный буфер не нужен

2024-02-29 16:17 UTC, tmvrus commented on internal/http/handlers/balance.go
> +	}
что будет если между получением баланса (GetBalance) и списанием  (AddWithdrawal) произойдет другое списание, которое нарушит условие b.Sum < w.Sum ?

2024-02-29 16:17 UTC, tmvrus commented on internal/http/handlers/register.go
> +	} else {
это else лишний, так как выше есть return

2024-02-29 16:17 UTC, tmvrus commented on internal/models/order.go
> +	db.AddOrder(ctx, o.Number, o.State, uid, o.Upload)
а есть если между CheckOrder и AddOrder другой запрос вставит заказ с таким же id

2024-02-29 16:17 UTC, tmvrus commented on internal/service/accrual/accrual.go
> +	if resp.StatusCode != http.StatusOK {
а еще может быть статус  429 Too Many Requests  нужно его учитывать

2024-03-04 12:57 UTC, Nchezhegova commented on internal/models/order.go
> +	db.AddOrder(ctx, o.Number, o.State, uid, o.Upload)
сделала номер заказа UNIQUE в бд

2024-03-04 14:01 UTC, Nchezhegova commented on internal/http/handlers/balance.go
> +	}
добавила mutex

2024-03-05 12:15 UTC, tmvrus approved these changes
своих тестов как не было так и нет(

2024-03-05 12:15 UTC, tmvrus commented on internal/http/handlers/balance.go
> +	mu.Lock()
работать будет, но только пока не будет запущена вторая копия приложения

2024-05-08 11:42 UTC, merged